In [1]:
import nltk
import h2o
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321 . connected.

--------------------------  ---------------------------------------------------------
H2O_cluster_uptime:         28 mins 59 secs
H2O_cluster_timezone:       Asia/Ho_Chi_Minh
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.34.0.3
H2O_cluster_version_age:    2 months and 4 days
H2O_cluster_name:           H2O_from_python_ACER_jsw948
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    5.269 Gb
H2O_cluster_total_cores:    8
H2O_cluster_allowed_cores:  8
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://localhost:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
H2O_API_Extensions:         Amazon S3, Algos, AutoML, Core V3, TargetEncoder, Core V4
Python_version:             3.9.7 final
--------------------------  ---------------------------------------------------------

In [ ]:
imported_model = h2o.import_mojo('C:\\Users\\ACER\\Desktop\\ml_project\\saved_models\\DRF_model_python_1639212866078_2.zip')
print('Model imported!')

In [11]:
input_str = input("Please enter your string: ")
print(input_str)

Hello VIeetnam it looks very cool

In [13]:
imported_model

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1639212866078_6


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,10.0,170.0,62490.0,4.0,5.0,4.994118,8.0,32.0,23.6

ModelMetricsMultinomialGeneric: generic
** Reported on train data. **

MSE: 0.082559394249025
RMSE: 0.287331505841293
LogLoss: 0.26973663794445063
Mean Per-Class Error: 0.443263316698414
AUC: NaN
AUCPR: NaN
Multinomial auc values: Table is not computed because it is disabled (model parameter 'auc_type' is set to AUTO or NONE) or due to domain size (maximum is 50 domains).
Multinomial auc_pr values: Table is not computed because it is disabled (model parameter 'auc_type' is set to AUTO or NONE) or due to domain size (maximum is 50 domains).

Confusion Matrix: Row labels: Actual class; Column labels: Predicted class

,B-art,B-eve,B-geo,B-gpe,B-nat,B-org,B-per,B-tim,I-art,I-eve,I-geo,I-gpe,I-nat,I-org,I-per,I-tim,O,prev-prev-lemma,Error,Rate
0,2.0,0.0,97.0,8.0,0.0,37.0,14.0,8.0,3.0,0.0,1.0,0.0,0.0,4.0,1.0,1.0,166.0,0.0,0.994152,340 / 342
1,0.0,67.0,49.0,3.0,0.0,51.0,14.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,4.0,82.0,0.0,0.754579,206 / 273
2,0.0,0.0,18445.0,374.0,2.0,884.0,369.0,168.0,1.0,0.0,4.0,2.0,0.0,38.0,225.0,44.0,9287.0,0.0,0.381932,"11,398 / 29,843"
3,0.0,0.0,3290.0,1422.0,0.0,331.0,146.0,25.0,0.0,0.0,103.0,0.0,0.0,142.0,91.0,20.0,7368.0,0.0,0.890091,"11,516 / 12,938"
4,0.0,0.0,51.0,5.0,2.0,20.0,4.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,101.0,0.0,0.989189,183 / 185
5,2.0,2.0,3490.0,230.0,0.0,4744.0,642.0,32.0,0.0,0.0,41.0,14.0,0.0,32.0,362.0,7.0,6456.0,0.0,0.704497,"11,310 / 16,054"
6,2.0,0.0,2288.0,111.0,0.0,408.0,5159.0,9.0,1.0,0.0,69.0,2.0,0.0,503.0,401.0,6.0,4475.0,0.0,0.615974,"8,275 / 13,434"
7,1.0,0.0,3938.0,78.0,0.0,35.0,26.0,3214.0,8.0,2.0,488.0,0.0,0.0,222.0,183.0,3.0,7759.0,0.0,0.798584,"12,743 / 15,957"
8,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,171.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,31.0,0.0,0.173913,36 / 207
9,0.0,0.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,217.0,1.0,0.0,0.0,0.0,2.0,0.0,11.0,0.0,0.072650,17 / 234
10,0.0,0.0,73.0,3.0,0.0,11.0,7.0,4.0,0.0,0.0,5137.0,0.0,0.0,20.0,24.0,0.0,574.0,0.0,0.122330,"716 / 5,853"
11,0.0,0.0,4.0,2.0,0.0,3.0,21.0,2.0,0.0,0.0,2.0,63.0,0.0,3.0,12.0,0.0,64.0,0.0,0.642045,113 / 176
12,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,57.0,1.0,1.0,0.0,4.0,0.0,0.123077,8 / 65
13,0.0,1.0,22.0,2.0,0.0,18.0,20.0,2.0,0.0,0.0,12.0,0.0,0.0,11153.0,49.0,0.0,1813.0,0.0,0.148106,"1,939 / 13,092"
14,0.0,0.0,47.0,8.0,0.0,29.0,29.0,9.0,0.0,0.0,34.0,0.0,0.0,51.0,12880.0,0.0,669.0,0.0,0.063681,"876 / 13,756"
15,0.0,2.0,68.0,5.0,0.0,11.0,6.0,46.0,0.0,0.0,2.0,0.0,0.0,12.0,15.0,2480.0,2285.0,0.0,0.497161,"2,452 / 4,932"
16,0.0,10.0,1824.0,367.0,0.0,709.0,581.0,250.0,1.0,4.0,90.0,19.0,0.0,286.0,571.0,68.0,700531.0,0.0,0.006777,"4,780 / 705,311"
17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0 / 0
18,7.0,82.0,33689.0,2618.0,4.0,7293.0,7039.0,3769.0,185.0,223.0,5986.0,100.0,57.0,12469.0,14822.0,2633.0,741676.0,0.0,0.080355,"66,908 / 832,652"

Top-10 Hit Ratios:

    k  hit_ratio
0   1   0.919645
1   2   0.957048
2   3   0.975893
3   4   0.987271
4   5   0.994482
5   6   0.997674
6   7   0.998711
7   8   0.999350
8   9   0.999688
9  10   0.999811

ModelMetricsMultinomialGeneric: generic
** Reported on validation data. **

MSE: 0.08149210825146673
RMSE: 0.2854682263430849
LogLoss: 0.26117317678599883
Mean Per-Class Error: 0.49829326870265866
AUC: NaN
AUCPR: NaN
Multinomial auc values: Table is not computed because it is disabled (model parameter 'auc_type' is set to AUTO or NONE) or due to domain size (maximum is 50 domains).
Multinomial auc_pr values: Table is not computed because it is disabled (model parameter 'auc_type' is set to AUTO or NONE) or due to domain size (maximum is 50 domains).

Confusion Matrix: Row labels: Actual class; Column labels: Predicted class

,B-art,B-eve,B-geo,B-gpe,B-nat,B-org,B-per,B-tim,I-art,I-eve,I-geo,I-gpe,I-nat,I-org,I-per,I-tim,O,prev-prev-lemma,Error,Rate
0,1.0,0.0,26.0,1.0,0.0,20.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,33.0,0.0,0.988764,88 / 89
1,0.0,14.0,20.0,0.0,0.0,15.0,5.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19.0,0.0,0.810811,60 / 74
2,0.0,0.0,4642.0,15.0,0.0,258.0,81.0,31.0,2.0,0.0,0.0,0.0,1.0,4.0,54.0,4.0,2324.0,0.0,0.374056,"2,774 / 7,416"
3,0.0,0.0,633.0,300.0,0.0,100.0,48.0,3.0,0.0,0.0,26.0,0.0,0.0,35.0,7.0,2.0,2169.0,0.0,0.909720,"3,023 / 3,323"
4,0.0,0.0,15.0,0.0,0.0,4.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,18.0,0.0,1.000000,40 / 40
5,0.0,1.0,810.0,8.0,0.0,1312.0,163.0,12.0,0.0,0.0,11.0,1.0,0.0,2.0,76.0,1.0,1593.0,0.0,0.671178,"2,678 / 3,990"
6,1.0,0.0,705.0,4.0,0.0,112.0,1331.0,2.0,0.0,0.0,23.0,0.0,0.0,115.0,109.0,0.0,1036.0,0.0,0.612856,"2,107 / 3,438"
7,0.0,0.0,920.0,0.0,0.0,6.0,1.0,802.0,1.0,1.0,128.0,0.0,0.0,52.0,40.0,0.0,2114.0,0.0,0.802706,"3,263 / 4,065"
8,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,62.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.114286,8 / 70
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,57.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.065574,4 / 61
10,0.0,0.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,1393.0,0.0,0.0,0.0,0.0,0.0,93.0,0.0,0.064473,"96 / 1,489"
11,0.0,0.0,2.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,21.0,0.0,0.0,2.0,0.0,19.0,0.0,0.588235,30 / 51
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,4.0,0.0,0.363636,4 / 11
13,0.0,0.0,2.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2925.0,2.0,0.0,408.0,0.0,0.124251,"415 / 3,340"
14,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3426.0,0.0,69.0,0.0,0.020023,"70 / 3,496"
15,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,718.0,590.0,0.0,0.452744,"594 / 1,312"
16,0.0,1.0,378.0,57.0,0.0,180.0,171.0,42.0,0.0,0.0,24.0,1.0,0.0,60.0,129.0,17.0,176636.0,0.0,0.005965,"1,060 / 177,696"
17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.000000,1 / 1
18,2.0,16.0,8156.0,385.0,0.0,2014.0,1812.0,895.0,65.0,58.0,1605.0,23.0,8.0,3197.0,3845.0,744.0,187137.0,0.0,0.077705,"16,315 / 209,962"

Top-10 Hit Ratios:

    k  hit_ratio
0   1   0.922295
1   2   0.959516
2   3   0.978434
3   4   0.989270
4   5   0.995728
5   6   0.998114
6   7   0.998847
7   8   0.999395
8   9   0.999729
9  10   0.999824

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_logloss,training_classification_error,training_auc,training_pr_auc,validation_rmse,validation_logloss,validation_classification_error,validation_auc,validation_pr_auc
0,,2021-12-11 15:58:02,0.006 sec,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,,2021-12-11 15:58:03,1.409 sec,1.0,0.278826,0.266659,0.078477,NaN,NaN,0.281219,0.271969,0.080481,NaN,NaN
2,,2021-12-11 15:58:05,2.756 sec,2.0,0.271239,0.249989,0.073890,NaN,NaN,0.269512,0.240371,0.073151,NaN,NaN
3,,2021-12-11 15:58:09,7.161 sec,6.0,0.279146,0.256104,0.078021,NaN,NaN,0.276581,0.244717,0.075333,NaN,NaN
4,,2021-12-11 15:58:14,12.249 sec,10.0,0.287332,0.269737,0.080355,NaN,NaN,0.285468,0.261173,0.077705,NaN,NaN

Variable Importances:

           variable  relative_importance  scaled_importance  percentage
0             shape        386552.312500           1.000000    0.447804
1              word        133135.703125           0.344418    0.154232
2          prev-iob        120417.414062           0.311516    0.139498
3        next-shape         43729.984375           0.113128    0.050659
4         next-word         38476.539062           0.099538    0.044573
5             lemma         33743.539062           0.087294    0.039090
6        prev-shape         27431.042969           0.070963    0.031778
7         prev-word         25501.341797           0.065971    0.029542
8        prev-lemma         12748.848633           0.032981    0.014769
9     prev-prev-iob         10611.209961           0.027451    0.012293
10  prev-prev-shape         10457.065430           0.027052    0.012114
11  prev-prev-lemma          6604.425293           0.017085    0.007651
12       next-lemma          6567.428711           0.016990    0.007608
13  next-next-shape          3540.809326           0.009160    0.004102
14   prev-prev-word          1941.513306           0.005023    0.002249
15   next-next-word          1060.287842           0.002743    0.001228
16  next-next-lemma           698.893250           0.001808    0.000810

In [15]:
import joblib
joblib.dump(imported_model, 'test_job_lib')

PicklingError: Can't pickle <class 'h2o.estimators.generic.H2OGenericEstimator'>: it's not the same object as h2o.estimators.generic.H2OGenericEstimator